"use client";

import { useEffect } from "react";
import { Amplify } from "aws-amplify";

/**
 * Configures the Amplify library with the generated outputs if available.
 *
 * In local mode (NEXT_PUBLIC_DATA_MODE=local) this component does nothing.
 * In Amplify mode, it tries to load amplify_outputs.json from the app root.
 * If the file is missing, Amplify calls will surface their own configuration
 * errors, which the repositories handle and display to the user.
 */

let amplifyOutputs: Record<string, unknown> | null = null;
try {
  // amplify_outputs.json is generated by `npx ampx sandbox` or a real
  // deployment. It lives at the app root (laboratorio_v3/apps/web).
  amplifyOutputs = require("../../amplify_outputs.json");
} catch {
  amplifyOutputs = null;
}

export function ConfigureAmplify() {
  useEffect(() => {
    if ((process.env.NEXT_PUBLIC_DATA_MODE ?? "local") !== "amplify") return;
    if (amplifyOutputs && Object.keys(amplifyOutputs).length > 0) {
      Amplify.configure(amplifyOutputs);
    }
  }, []);

  return null;
}
